# Generated by Django 3.0.7 on 2020-06-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField(blank=True)),
                ('vender_name', models.CharField(blank=True, max_length=50)),
                ('invoice_date', models.DateField(blank=True)),
                ('pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
