# Generated by Django 3.0.7 on 2020-06-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0002_invoicedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf/'),
        ),
    ]
