# Generated by Django 3.0.7 on 2020-06-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0003_auto_20200607_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='agent_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
