# Generated by Django 3.0.7 on 2020-06-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0004_invoicedetails_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
