# Generated by Django 3.0.7 on 2020-06-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0005_auto_20200607_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
