# Generated by Django 3.0.7 on 2020-06-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0006_auto_20200607_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='upload_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
