# Generated by Django 3.0.7 on 2020-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0007_invoicedetails_upload_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, max_length=50)),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('item_description', models.CharField(blank=True, max_length=50)),
                ('item_quantity', models.IntegerField(blank=True, null=True)),
                ('item_rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
