# Generated by Django 3.0.7 on 2020-06-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0008_itemdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
